"""add avatar_hash to user

Revision ID: 533981255450
Revises: ec2d83057fed
Create Date: 2025-09-25 22:57:29.451342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533981255450'
down_revision = 'ec2d83057fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###
